name: flutter_sensors
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sensors: ^0.4.0
  firebase_core: ^0.2.5+1
  cloud_firestore: ^0.8.2+3
#  firebase_database: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

